---

- name: Install nginx
  apt:
    pkg: nginx
    update_cache: yes
    state: latest

- name: Remove the default configuration
  file:
    path: '{{ nginx_sites_enabled }}/default'
    state: absent

- name: Push site configurations
  notify: restart nginx
  template:
    src: site.j2
    dest: '{{ nginx_sites_available }}/{{ item.name }}'
  with_items: nginx_sites

- name: Enable the site configurations
  notify: restart nginx
  file:
    src: '{{ nginx_sites_available }}/{{ item.name }}'
    dest: '{{ nginx_sites_enabled }}/{{ item.site }}'
    state: link
  with_items: nginx_sites
