---

dependencies:


  - role: osp
    tags: osp


  - role: uwsgi
    tags: uwsgi

    uwsgi_programs:

      - name: osp-www
        pythonpath: '{{ osp_src }}'
        base: '{{ osp_src }}'
        home: '{{ osp_src }}/env'
        socket: 127.0.0.1:4242
        module: osp.www.app
        callable: app


  - role: supervisor
    tags: supervisor

    supervisor_programs:

      - name: osp-www-prod
        command: '{{ osp_www_start_prod }}'

      - name: osp-www-dev
        command: '{{ osp_www_start_dev }}'


  - role: nginx
    tags: nginx

    nginx_sites:

      - name: osp-www
        site: default
        uwsgi_pass: 127.0.0.1:4242
        static:
          root: '{{ osp_www_src }}'
          path: static
