---

- name: Provision a worker set
  hosts: localhost

  vars_files:
    - vars/local.yml

  tasks:

    - name: Start the data repository
      register: servers
      ec2:

        image: '{{ ec2_image }}'
        keypair: '{{ ec2_keypair }}'
        group: '{{ ec2_group }}'
        region: '{{ ec2_region }}'

        instance_type: '{{ ec2_server_instance_type }}'
        vpc_subnet_id: '{{ ec2_subnet_id }}'

        assign_public_ip: yes
        wait: yes

        volumes:
          - device_name: /dev/sda1
            volume_size: '{{ ec2_server_volume_size }}'

        exact_count: '{{ ec2_server_count }}'

        instance_tags:
          Name: osp-server
          user: '{{ ec2_namespace }}'
          osp: server

        count_tag:
          user: '{{ ec2_namespace }}'
          osp: server

    - name: Start the workers
      register: workers
      ec2:

        image: '{{ ec2_image }}'
        keypair: '{{ ec2_keypair }}'
        group: '{{ ec2_group }}'
        region: '{{ ec2_region }}'

        instance_type: '{{ ec2_worker_instance_type }}'
        vpc_subnet_id: '{{ ec2_subnet_id }}'

        assign_public_ip: yes
        wait: yes

        exact_count: '{{ ec2_worker_count }}'

        instance_tags:
          Name: osp-worker
          user: '{{ ec2_namespace }}'
          osp: worker

        count_tag:
          user: '{{ ec2_namespace }}'
          osp: worker

    - name: Attach the OSP volume
      ec2_vol:

        instance: '{{ item.id }}'
        snapshot: '{{ ec2_osp_snapshot }}'
        region: '{{ ec2_region }}'
        volume_type: '{{ ec2_volume_type }}'
        iops: '{{ ec2_iops }}'

      with_flattened:
        - workers.instances
        - servers.instances
