---

- name: Push Supervisor configurations
  template:
    src: supervisor/{{ item }}.conf.j2
    dest: /etc/supervisor/conf.d/{{ item }}.conf
  with_items:
    - rq-worker
    - osp-api

- name: Reload Supervisor programs
  shell: supervisorctl reload
