---

- name: Push Supervisor configurations
  template:
    src: supervisor/{{ item }}.conf.j2
    dest: /etc/supervisor/conf.d/{{ item }}.conf
  with_items:
    - rq-worker
    - osp-worker

- name: Reload Supervisor
  shell: supervisorctl reload

- name: Wait for Supervisor
  pause: seconds=3

- name: Start Supervisor programs
  supervisorctl:
    name: '{{ item }}'
    state: restarted
  with_items: osp_worker_procs
