---

osp_repo: https://github.com/davidmcclure/open-syllabus-project.git
osp_branch: master
osp_src: /home/{{ ansible_ssh_user }}/osp
osp_numprocs: 4
osp_init_db: yes

# Set in local vars with `osp_data_host`.
__osp_data_host: localhost

osp_profile:
  - . osp/env/bin/activate

osp_db_modules:
  - corpus
  - fields
  - citations
  - inst

osp_tika_url: http://apache.mesi.com.ar/tika/tika-server-1.11.jar
osp_tika_path: /etc/tika
osp_tika_jar: tika-server-1.11.jar
