---

dependencies:


  - role: osp
    tags: osp


  - role: uwsgi
    tags: uwsgi

    uwsgi_programs:

      - name: osp-worker
        pythonpath: '{{ osp_src }}'
        base: '{{ osp_src }}'
        home: '{{ osp_src }}/env'
        socket: 127.0.0.1:4242
        module: osp.workers.server
        callable: app


  - role: supervisor
    tags: supervisor

    supervisor_programs:

      - name: osp-worker
        command: '{{ osp_worker_start_api }}'

      - name: rq-worker
        command: '{{ osp_worker_start_rqworker }}'
        numprocs: '{{ osp_numprocs }}'


  - role: nginx
    tags: nginx

    nginx_sites:

      - name: osp-worker
        site: default
        uwsgi_pass: 127.0.0.1:4242
