---

- name: Push Supervisor configurations
  template:
    src: supervisor/{{ item }}.conf.j2
    dest: /etc/supervisor/conf.d/{{ item }}.conf
  with_items:
    - tika-server
    - es-test

- name: Reload Supervisor programs
  shell: supervisorctl reload
