---

- name: Install system dependencies
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - pkg-config
    - python-virtualenv
    - python3-setuptools
    - python3-dev
    - libfreetype6-dev
    - libpq-dev
    - libxslt1-dev
    - libxml2-dev
    - libgraphicsmagick++1-dev
    - libboost-python-dev

- name: Install SciPy build dependencies
  command: apt-get -y build-dep python3-scipy
