---

dependencies:


  - role: common
    tags: common


  - role: redis
    tags: redis


  - role: elasticsearch
    tags: elasticsearch


  - role: postgresql
    tags: postgresql
    become: yes

    postgresql_version: 9.5
    postgresql_ext_install_contrib: yes
    postgresql_max_connections: 500
    postgresql_client_encoding: utf8

    postgresql_databases:
      - name: osp
      - name: osp-test

    postgresql_users:
      - name: osp
        pass: '{{ osp_db_pass }}'

    postgresql_user_privileges:
      - name: osp
        db: osp
        priv: 'ALL'

    postgresql_listen_addresses:
      - '*'

    postgresql_pg_hba_custom:
      - type: host
        database: osp
        user: all
        address: all
        method: md5
        comment: ''


  - role: supervisor
    tags: supervisor

    supervisor_reset_programs: true

    supervisor_programs:

      - name: tika-server
        command: java -jar {{ osp_tika_path }}/{{ osp_tika_jar }}

      - name: es-test
        command: >
          /usr/share/elasticsearch/bin/elasticsearch
          --config=/etc/elasticsearch-test/elasticsearch.yml
