---

- name: Set permissions on data dirs
  file:
    state: directory
    path: '{{ item }}'
    owner: '{{ es_user }}'
    group: '{{ es_group }}'
    mode: 0700
    recurse: yes
  with_items:
    - '{{ es_prod_data_dir }}'
    - '{{ es_test_data_dir }}'

- name: Set permissions on conf dirs
  file:
    state: directory
    path: '{{ item }}'
    owner: '{{ es_user }}'
    group: '{{ es_group }}'
    recurse: yes
  with_items:
    - /etc/elasticsearch
    - /etc/elasticsearch-test

- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
